

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ÄlytaloWEB.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class JohaMeriSQL2Entities : DbContext
{
    public JohaMeriSQL2Entities()
        : base("name=JohaMeriSQL2Entities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<TaloIlma> TaloIlma { get; set; }

    public virtual DbSet<TaloLampo> TaloLampo { get; set; }

    public virtual DbSet<TaloSauna> TaloSauna { get; set; }

    public virtual DbSet<TaloValo> TaloValo { get; set; }

}

}

