
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ÄlytaloWEB.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TaloValo
{

    public int Valo_ID { get; set; }

    public string Huone { get; set; }

    public string ValaisinType { get; set; }

    public string Lamppu_ID { get; set; }

    public bool ValoTilaOff { get; set; }

    public bool Valo33 { get; set; }

    public bool Valo66 { get; set; }

    public bool Valo100 { get; set; }

    public Nullable<System.DateTime> ValoOn33 { get; set; }

    public Nullable<System.DateTime> ValoOn66 { get; set; }

    public Nullable<System.DateTime> ValoOn100 { get; set; }

    public Nullable<System.DateTime> ValoOff { get; set; }

}

}
