
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ÄlytaloWEB.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TaloSauna
{

    public int Sauna_ID { get; set; }

    public Nullable<int> SaunaNro { get; set; }

    public string SaunanNimi { get; set; }

    public string SaunaTavoiteLampotila { get; set; }

    public string SaunaNykyLampotila { get; set; }

    public bool SaunanTila { get; set; }

    public Nullable<System.DateTime> SaunaStart { get; set; }

    public Nullable<System.DateTime> SaunaStop { get; set; }

}

}
