
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ÄlytaloWEB.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TaloIlma
{

    public int Ilma_ID { get; set; }

    public string Huone { get; set; }

    public bool IlmaTilaOff { get; set; }

    public bool Ilma1 { get; set; }

    public bool Ilma2 { get; set; }

    public bool Ilma3 { get; set; }

    public bool Ilma4 { get; set; }

    public Nullable<System.DateTime> IlmaOn1 { get; set; }

    public Nullable<System.DateTime> IlmaOn2 { get; set; }

    public Nullable<System.DateTime> IlmaOn3 { get; set; }

    public Nullable<System.DateTime> IlmaOn4 { get; set; }

    public Nullable<System.DateTime> IlmaOff { get; set; }

}

}
